#!/bin/sh -eu
#
# NAME
#        adb-screencap -- capture an android device's screen and pull the picture using adb
#
# SYNOPSIS
#        adb-screencap [-s <specific device>]
#
# DESCRIPTION
#
#        The following options are available:
#
#        -s <specific device>   directs command to the device or emulator with the given
#                                   serial number or qualifier. Overrides ANDROID_SERIAL
#

SERIAL=
DATE=`\date '+%y%m%d%H%M%S'`

# 引数のオプションを取得して OPTION に入れてループ
while getopts s: OPTION # s: で -s <arg> を受ける
do
    case $OPTION in
        s) # -s があったら
            SERIAL=$OPTARG # -s <arg> の <arg> を $OPTARG で取得できる
            ;; # break;
    esac
done

# ${PARAM:+VAR} で PARAM に非ヌル値設定されている場合のみ VAR を展開する
\adb ${SERIAL:+-s $SERIAL} shell screencap -p /sdcard/screen-${DATE}.png
\adb ${SERIAL:+-s $SERIAL} pull /sdcard/screen-${DATE}.png
\adb ${SERIAL:+-s $SERIAL} shell rm /sdcard/screen-${DATE}.png

\echo screen-${DATE}.png